
import {
  Sparkles,
  Heart,
  Droplets,
  Shield,
  Zap,
  Activity,
} from "lucide-react";

export const BADGES = [
  {
    id: "first_step",
    name: "初次觉醒",
    desc: "完成第一次训练",
    target: 1,
    type: "workouts",
    emoji: "🌱",
  },
  {
    id: "ten_workouts",
    name: "十全十美",
    desc: "完成10次训练",
    target: 10,
    type: "workouts",
    emoji: "🔟",
  },
  {
    id: "fifty_workouts",
    name: "半百征途",
    desc: "完成50次训练",
    target: 50,
    type: "workouts",
    emoji: "🏅",
  },
  {
    id: "hundred_workouts",
    name: "百炼成钢",
    desc: "完成100次训练",
    target: 100,
    type: "workouts",
    emoji: "💎",
  },
  {
    id: "streak_3",
    name: "三日之约",
    desc: "连续打卡3天",
    target: 3,
    type: "streak",
    emoji: "🔥",
  },
  {
    id: "streak_7",
    name: "自律王者",
    desc: "连续打卡7天",
    target: 7,
    type: "streak",
    emoji: "👑",
  },
  {
    id: "streak_14",
    name: "钢铁意志",
    desc: "连续打卡14天",
    target: 14,
    type: "streak",
    emoji: "⚔️",
  },
  {
    id: "streak_30",
    name: "传奇毅力",
    desc: "连续打卡30天",
    target: 30,
    type: "streak",
    emoji: "🏆",
  },
  {
    id: "master_60",
    name: "渐入佳境",
    desc: "累计训练60分钟",
    target: 60,
    type: "minutes",
    emoji: "⏱️",
  },
  {
    id: "master_300",
    name: "核心掌控",
    desc: "累计训练300分钟",
    target: 300,
    type: "minutes",
    emoji: "🎯",
  },
  {
    id: "master_600",
    name: "殿堂大师",
    desc: "累计训练600分钟",
    target: 600,
    type: "minutes",
    emoji: "🌟",
  },
  {
    id: "early_bird",
    name: "早起鸟儿",
    desc: "在早上6-8点完成训练",
    target: 1,
    type: "special",
    emoji: "🐦",
  },
];

export const THEMES = {
  female: {
    title: "Secret Garden",
    subtitle: "你的私密健康花园",
    bgClass: "bg-[#120E15]",
    gradientClass: "text-gradient-rose",
    glassClass: "glass-panel-rose",
    blob1: "bg-rose-900/20",
    blob2: "bg-purple-900/20",
    primaryColor: "#FDA4AF",
    ringColor: "#E11D48",
    programs: [
      {
        id: "daily",
        name: "日常唤醒保养",
        desc: "每天3分钟，预防松弛，保持私密年轻态。",
        icon: <Sparkles className="w-4 h-4" />,
        contractTime: 3,
        restTime: 3,
        cycles: 10,
        color: "#FBCFE8",
        glowColor: "rgba(244, 114, 182, 0.4)",
      },
      {
        id: "tighten",
        name: "紧致提升进阶",
        desc: "强化盆底肌群，提升伴侣亲密体验与自我掌控感。",
        icon: <Heart className="w-4 h-4" />,
        contractTime: 5,
        restTime: 5,
        cycles: 15,
        color: "#E9D5FF",
        glowColor: "rgba(192, 132, 252, 0.4)",
      },
      {
        id: "postpartum",
        name: "产后温和修复",
        desc: "专为产后妈妈设计，加长放松时间，改善漏尿尴尬。",
        icon: <Droplets className="w-4 h-4" />,
        contractTime: 4,
        restTime: 6,
        cycles: 12,
        color: "#BAE6FD",
        glowColor: "rgba(56, 189, 248, 0.4)",
      },
    ],
    guidance: {
      ready: ["准备", "深呼吸"],
      contract: [
        "收紧",
        "吸气",
        "保持",
      ],
      rest: [
        "放松",
        "呼气",
        "休息",
      ],
    },
    tipTitle: "如何找到盆底肌？",
    tipContent: [
      "1. 想象正在憋尿：尝试在排尿中途突然停止，那一瞬间收紧的肌肉就是盆底肌。（注意：仅用于寻找感觉，不要经常在排尿时练习）。",
      "2. 想象阻止排气：收紧肛门周围的肌肉，就像在公共场合试图憋住放屁一样。",
      "3. 避免错误发力：练习时，你的大腿、臀部和腹部应该是放松的。如果肚子紧绷，说明发力错误。",
    ],
  },
  "female-light": {
    title: "Secret Garden",
    subtitle: "你的私密健康花园 (浅色模式)",
    bgClass: "bg-[#FFF0F5]", // 淡粉白
    gradientClass: "text-rose-600 drop-shadow-sm",
    glassClass: "bg-white/80 backdrop-blur-xl border border-rose-100 shadow-sm",
    blob1: "bg-rose-300/40",
    blob2: "bg-pink-300/40",
    primaryColor: "#E11D48",
    ringColor: "#E11D48",
    programs: [
      {
        id: "daily",
        name: "日常唤醒保养",
        desc: "每天3分钟，预防松弛，保持私密年轻态。",
        icon: <Sparkles className="w-4 h-4 text-rose-500" />,
        contractTime: 3,
        restTime: 3,
        cycles: 10,
        color: "#FBCFE8",
        glowColor: "rgba(244, 114, 182, 0.4)",
      },
      {
        id: "tighten",
        name: "紧致提升进阶",
        desc: "强化盆底肌群，提升伴侣亲密体验与自我掌控感。",
        icon: <Heart className="w-4 h-4 text-rose-500" />,
        contractTime: 5,
        restTime: 5,
        cycles: 15,
        color: "#E9D5FF",
        glowColor: "rgba(192, 132, 252, 0.4)",
      },
      {
        id: "postpartum",
        name: "产后温和修复",
        desc: "专为产后妈妈设计，加长放松时间，改善漏尿尴尬。",
        icon: <Droplets className="w-4 h-4 text-rose-500" />,
        contractTime: 4,
        restTime: 6,
        cycles: 12,
        color: "#BAE6FD",
        glowColor: "rgba(56, 189, 248, 0.4)",
      },
    ],
    guidance: {
      ready: ["准备", "深呼吸"],
      contract: [
        "收紧",
        "吸气",
        "保持",
      ],
      rest: [
        "放松",
        "呼气",
        "休息",
      ],
    },
    tipTitle: "如何找到盆底肌？",
    tipContent: [
      "1. 想象正在憋尿：尝试在排尿中途突然停止，那一瞬间收紧的肌肉就是盆底肌。（注意：仅用于寻找感觉，不要经常在排尿时练习）。",
      "2. 想象阻止排气：收紧肛门周围的肌肉，就像在公共场合试图憋住放屁一样。",
      "3. 避免错误发力：练习时，你的大腿、臀部和腹部应该是放松的。如果肚子紧绷，说明发力错误。",
    ],
  },
  male: {
    title: "Deep Control",
    subtitle: "男性的核心掌控引擎",
    bgClass: "bg-[#0B1120]",
    gradientClass: "text-gradient-ocean",
    glassClass: "glass-panel-ocean",
    blob1: "bg-cyan-900/20",
    blob2: "bg-blue-900/20",
    primaryColor: "#7DD3FC",
    ringColor: "#0284C7",
    programs: [
      {
        id: "m_daily",
        name: "基础唤醒控制",
        desc: "激活盆底肌群，建立神经连接，找回发力感。",
        icon: <Shield className="w-4 h-4" />,
        contractTime: 3,
        restTime: 3,
        cycles: 10,
        color: "#BAE6FD",
        glowColor: "rgba(56, 189, 248, 0.4)",
      },
      {
        id: "m_stamina",
        name: "持久力强化进阶",
        desc: "提升肌肉耐力与爆发力，增强核心掌控与自信。",
        icon: <Zap className="w-4 h-4" />,
        contractTime: 5,
        restTime: 5,
        cycles: 15,
        color: "#93C5FD",
        glowColor: "rgba(59, 130, 246, 0.4)",
      },
      {
        id: "m_health",
        name: "前列腺健康保养",
        desc: "促进局部血液循环，预防久坐带来的健康隐患。",
        icon: <Activity className="w-4 h-4" />,
        contractTime: 4,
        restTime: 6,
        cycles: 12,
        color: "#A7F3D0",
        glowColor: "rgba(16, 185, 129, 0.4)",
      },
    ],
    guidance: {
      ready: ["准备", "深呼吸"],
      contract: [
        "收紧",
        "吸气",
        "保持",
      ],
      rest: [
        "放松",
        "呼气",
        "休息",
      ],
    },
    tipTitle: "如何找到盆底肌？(男性)",
    tipContent: [
      "1. 想象中断排尿：在排尿时尝试突然停止水流，此时发力的肌肉群就是盆底肌。（注意：仅用于初期寻找感觉，切勿频繁在排尿时练习）。",
      "2. 想象阻止排气：收紧肛门括约肌，就像试图憋住放屁一样，同时感觉阴茎根部有轻微的向内回缩感。",
      "3. 避免代偿发力：练习时，你的腹肌、大腿和臀部肌肉应该是放松的。如果肚子明显用力，说明发力位置不对。",
    ],
  },
  "male-light": {
    title: "Deep Control",
    subtitle: "男性的核心掌控引擎 (浅色模式)",
    bgClass: "bg-[#F0F9FF]", // 极地蓝白
    gradientClass: "text-sky-700 drop-shadow-sm",
    glassClass: "bg-white/80 backdrop-blur-xl border border-sky-100 shadow-sm",
    blob1: "bg-sky-300/40",
    blob2: "bg-blue-300/40",
    primaryColor: "#0284C7",
    ringColor: "#0284C7",
    programs: [
      {
        id: "m_daily",
        name: "基础唤醒控制",
        desc: "激活盆底肌群，建立神经连接，找回发力感。",
        icon: <Shield className="w-4 h-4 text-sky-600" />,
        contractTime: 3,
        restTime: 3,
        cycles: 10,
        color: "#BAE6FD",
        glowColor: "rgba(56, 189, 248, 0.4)",
      },
      {
        id: "m_stamina",
        name: "持久力强化进阶",
        desc: "提升肌肉耐力与爆发力，增强核心掌控与自信。",
        icon: <Zap className="w-4 h-4 text-sky-600" />,
        contractTime: 5,
        restTime: 5,
        cycles: 15,
        color: "#93C5FD",
        glowColor: "rgba(59, 130, 246, 0.4)",
      },
      {
        id: "m_health",
        name: "前列腺健康保养",
        desc: "促进局部血液循环，预防久坐带来的健康隐患。",
        icon: <Activity className="w-4 h-4 text-sky-600" />,
        contractTime: 4,
        restTime: 6,
        cycles: 12,
        color: "#A7F3D0",
        glowColor: "rgba(16, 185, 129, 0.4)",
      },
    ],
    guidance: {
      ready: ["准备", "深呼吸"],
      contract: [
        "收紧",
        "吸气",
        "保持",
      ],
      rest: [
        "放松",
        "呼气",
        "休息",
      ],
    },
    tipTitle: "如何找到盆底肌？(男性)",
    tipContent: [
      "1. 想象中断排尿：在排尿时尝试突然停止水流，此时发力的肌肉群就是盆底肌。（注意：仅用于初期寻找感觉，切勿频繁在排尿时练习）。",
      "2. 想象阻止排气：收紧肛门括约肌，就像试图憋住放屁一样，同时感觉阴茎根部有轻微的向内回缩感。",
      "3. 避免代偿发力：练习时，你的腹肌、大腿和臀部肌肉应该是放松的。如果肚子明显用力，说明发力位置不对。",
    ],
  },
};
